### ISSUE TITLE
Does not work in Python 3

### ISSUE THREAD

**Issue by eefret** [arcturial/clickatell-python#1]
Hi, I tried to use this lib to send a message and it gives me this stacktrace, it appears that the urllib in python3 uses the method in another way

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eefret/Workspace/python/lifewall-server/env/lib/python3.4/site-packages/clickatell/http/__init__.py", line 42, in sendMessage
    content = self.parseLegacy(self.request('http/sendmsg', data));
  File "/home/eefret/Workspace/python/lifewall-server/env/lib/python3.4/site-packages/clickatell/http/__init__.py", line 29, in request
    return Transport.request(self, action, data, headers, method)
  File "/home/eefret/Workspace/python/lifewall-server/env/lib/python3.4/site-packages/clickatell/__init__.py", line 118, in request
    body = urllib.urlencode(data)
AttributeError: 'module' object has no attribute 'urlencode'
```

**Comment by arcturial** [comment]
Hey, it's currently not supported in version 3. I will see if I can add some support for this and bump it a version. I will keep you posted on the progress.

**Comment by arcturial** [comment]
I implemented support for version 3.

Give https://github.com/arcturial/clickatell-python/tree/0.0.2 a try and let me know if that works for you.

**Comment by eefret** [comment]
Its sending the message but now I have this StackTrace, but its sending them.

``` python
>>> response = clickatell.sendMessage(['18098562610'], "ola k ase")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eefret/Downloads/clickatell-python-0.0.2/clickatell/http/__init__.py", line 42, in sendMessage
    content = self.parseLegacy(self.request('http/sendmsg', data));
  File "/home/eefret/Downloads/clickatell-python-0.0.2/clickatell/__init__.py", line 64, in parseLegacy
    lines = response['body'].strip('\n').split('\n')
TypeError: Type str doesn't support the buffer API
>>> print(response)
```

**Comment by arcturial** [comment]
Dammit, I will add a test for that issue and bump the revision again. Stay tuned ;)

**Comment by arcturial** [comment]
Issue should be sorted in the latest tag https://github.com/arcturial/clickatell-python/tree/0.0.3

Turns out Python 3 returns a buffer instead of a string when doing an HTTP request, I made sure to parse the the response to string before running string operations on it.

**Comment by arcturial** [comment]
I think this might have caused some other problems though.

**Comment by eefret** [comment]
that's why in my workplace I use requests library. simple, powerfull, same api for all versions

**Comment by arcturial** [comment]
You talking about this one: http://docs.python-requests.org/en/latest/?

**Comment by eefret** [comment]
Yeah, that one, I can give u a hand if u need it :D

**Comment by arcturial** [comment]
Have a look at this one: https://github.com/arcturial/clickatell-python/tree/refactor-request

I refactored the request method a to use your suggested library. It seems to be much easier in terms of portability. Feel free to make some changes if you see any potential issues or improvements. If this works for you I will create a new distribution tomorrow.

**Comment by eefret** [comment]
Yeah will try to optimize some stuff, I know the library very well, will try and test this now, Thanks...

**Comment by eefret** [comment]
Cool, Working nicely, Thanks Chris
