### ISSUE TITLE
Cannot import Transport

### ISSUE THREAD

**Issue by eefret** [arcturial/clickatell-python#3]
Cannot import Transport, this happens in the pip version

``` python
Traceback (most recent call last):
  File "lwserver/main.py", line 7, in <module>
    from lwserver import blueprints
  File "/home/eefret/Workspace/python/lifewall-server/lwserver/blueprints/__init__.py", line 1, in <module>
    from . import api, user, posts, comments, login
  File "/home/eefret/Workspace/python/lifewall-server/lwserver/blueprints/api.py", line 15, in <module>
    from clickatell.http import Http as Client
  File "/home/eefret/Workspace/python/lifewall-server/env/lib/python3.4/site-packages/clickatell/http/__init__.py", line 1, in <module>
    from clickatell import Transport
ImportError: cannot import name 'Transport'
```

**Comment by eefret** [comment]
I have checked the site-packages and theres no **init**.py in the main clickatell folder

**Comment by arcturial** [comment]
Does this happen if you install it via pip? Version 0.1.1?

**Comment by eefret** [comment]
Yep, as you can see its under my  site-packages,  please check that out.

**Comment by arcturial** [comment]
When I install it via pip, the following files exist in my dist-packages (site-packages):

exception.py
http
**init**.py
**pycache**
rest

Did you perhaps have any issues during install? If I inspect the tar.gz file on pypi it contains the **init**.py file missing from your folder.

**Comment by arcturial** [comment]
Any luck getting it to work? Not sure what I can do/change to help out.

**Comment by eefret** [comment]
I made it work, uninstalling and installing again, seems like pip was trolling me. Sorry for the inconveniences. I'm making a Clickatell API for Go because we will change to that language and I have learned about of this HTTP API with your library, thanks.

**Comment by arcturial** [comment]
Let me know if you need any help, I have been wanting to do some work in Go.
