### ISSUE TITLE
Library is not versioned

### ISSUE THREAD

**Issue by euri16** [arcturial/clickatell-python#4]
Could you please version this library in order for me to use it properly?

**Comment by arcturial** [comment]
The library already contains different tags for different release points and it has been uploaded with various versions to pypi with (0.1.1 being the latest)[https://pypi.python.org/pypi/clickatell/0.1.1]. Can you please elaborate, did I perhaps miss something?

**Comment by arcturial** [comment]
The library has been versioned on PyPi ad a few releases have already been published. Resolving this until further information is provided.
