### ISSUE TITLE
Sender-id?

### ISSUE THREAD

**Issue by aleyrizvi** [arcturial/clickatell-python#5]
Is it possible to send sender CLI with rest ?

**Comment by arcturial** [comment]
Yeah, the third parameter for `sendMessage` is an optional string of extra parameters. The parameter you are looking for is "from".

``` php

response = clickatell.sendMessage(['1111111111'], "My Message", { "from": 1234567890 })

```

**Comment by aleyrizvi** [comment]
Thank you Chris :)
