### ISSUE TITLE
Unicode Hex issue

### ISSUE THREAD

**Issue by aleyrizvi** [arcturial/clickatell-python#6]
Hi, 
I am not able to send unicode sms. It gives me decode exception. Please look at the following:

> > > c
> > > "\xff\xfeP\x00o\x00\xe8\x00m\x00e\x00s\x00 \x00d\x00'\x00a\x00m\x00o\x00u\x00r\x00 \x00F\x00r\x00a\x00n\x00\xe7\x00a\x00i\x00s\x00 \x00&\x00 \x00A\x00n\x00g\x00l\x00a\x00i\x00s\x00,\x00 \x00L\x00o\x00v\x00e\x00 \x00r\x00o\x00m\x00a\x00n\x00t\x00i\x00c\x00 \x00p\x00o\x00e\x00m\x00s\x00 \x00F\x00r\x00e\x00n\x00c\x00h\x00 \x00&\x00 \x00E\x00n\x00g\x00l\x00i\x00s\x00h\x00 \x00&\x00 \x00"
> > > A.sendMessage(['923342461111'],c , {"unicode" : 1})
> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > >   File "/Users/alex/Documents/projects/nom_rest_api/env/lib/python2.7/site-packages/clickatell/rest/**init**.py", line 42, in sendMessage
> > >     content = self.parseRest(self.request('rest/message', data, {}, 'POST'));
> > >   File "/Users/alex/Documents/projects/nom_rest_api/env/lib/python2.7/site-packages/clickatell/rest/**init**.py", line 29, in request
> > >     return Transport.request(self, action, data, headers, method)
> > >   File "/Users/alex/Documents/projects/nom_rest_api/env/lib/python2.7/site-packages/clickatell/**init**.py", line 130, in request
> > >     resp = func(url, params=data, data=json.dumps(data), headers=headers)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 243, in dumps
> > >     return _default_encoder.encode(obj)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
> > >     chunks = self.iterencode(o, _one_shot=True)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
> > >     return _iterencode(o, 0)
> > > UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by aleyrizvi** [comment]
can you give me an example to send text: Félix Arvers with french accent?

Clickatell does not like to provide python example :)

**Comment by arcturial** [comment]
Hi

Clickatell expects the unicode in a hex representation. You can convert it like so:

```
import binascii

c = "\xff\xfeP\x00o\x00\xe8\x00m\x00e\x00s\x00 \x00d\x00'\x00a\x00m\x00o\x00u\x00r\x00 \x00F\x00r\x00a\x00n\x00\xe7\x00a\x00i\x00s\x00 \x00&\x00 \x00A\x00n\x00g\x00l\x00a\x00i\x00s\x00,\x00 \x00L\x00o\x00v\x00e\x00 \x00r\x00o\x00m\x00a\x00n\x00t\x00i\x00c\x00 \x00p\x00o\x00e\x00m\x00s\x00 \x00F\x00r\x00e\x00n\x00c\x00h\x00 \x00&\x00 \x00E\x00n\x00g\x00l\x00i\x00s\x00h\x00 \x00&\x00 \x00"

c = binascii.hexlify(c)
```

You can now pass the variable `c` to the `sendMessage` call along with the `{ "unicode": 1 }` paramter. However, I noticed that the UTF-16 string you provided had some extra characters that caused rendering issues on the mobile phone. I removed the extra characters like so:

```
c = "\x00P\x00o\x00\xe8\x00m\x00e\x00s\x00 \x00d\x00'\x00a\x00m\x00o\x00u\x00r\x00 \x00F\x00r\x00a\x00n\x00\xe7\x00a\x00i\x00s\x00 \x00&\x00 \x00A\x00n\x00g\x00l\x00a\x00i\x00s\x00,\x00 \x00L\x00o\x00v\x00e\x00 \x00r\x00o\x00m\x00a\x00n\x00t\x00i\x00c\x00 \x00p\x00o\x00e\x00m\x00s\x00 \x00F\x00r\x00e\x00n\x00c\x00h\x00 \x00&\x00 \x00E\x00n\x00g\x00l\x00i\x00s\x00h\x00 \x00&"
```

After testing it, it successfully delivered the message:

"Poèmes d'amour Français & Anglais, Love romantic poems French & English &"

**Comment by aleyrizvi** [comment]
That was perfect :)

Thank you once again for the support.
